apiVersion: v1
kind: Service
metadata:
  name: userservice-nodeport
spec:
  type: NodePort
  selector:
    app: userservice
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30081
      
